### ISSUE TITLE
HTTP auth failed

### ISSUE THREAD

**Issue by henrymei** [wernight/docker-ngrok#10]
When HTTP auth is specified (i.e. `-auth="admin:admin"`), it looks like the credentials aren't being accepted for some reason.

**Comment by wernight** [comment]
Try setting NGROK_AUTH as described in README.

**Comment by henrymei** [comment]
I believe I have (via docker-compose). I'm using a custom subdomain that routes properly, but the basic auth credentials won't auth for some reason.

**Comment by MQasimSarfraz** [comment]
I have a similar issue. Seems to me some quoting issue with

`'-auth="seat:findme"'`

because running it manually in container works as:

`-auth="seat:findme"`
