### ISSUE TITLE
Failed to complete tunnel connection

### ISSUE THREAD

**Issue by niccolomeloni** [wernight/docker-ngrok#14]
Hi,

i am a dockerized apache web server running with docker-compose. In order to get tunneling i type `docker run --rm -it -p 4040:4040 --link dockerizedapp_apache:http --network dockerizedapp_default  wernight/ngrok`. Then i connect from my browser to `localhost:4040` but trying to navigate to the ngrok link i get following problem:

```
Failed to complete tunnel connection

The connection to http://blablabla.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:80.

Make sure that a web service is running on localhost:80 and that it is a valid address.

The error encountered was: dial tcp [::1]:80: getsockopt: connection refused
```

Am i doing something wrong?

Thank you for your work.

**Comment by wernight** [comment]
It's probably not on localhost but on another container, unless you run with `--net=host`.
