### ISSUE TITLE
Update repository link

### ISSUE THREAD

**Issue by kytwb** [wernight/docker-ngrok#19]
From: https://registry.hub.docker.com/u/wernight/ngrok
To: https://hub.docker.com/r/wernight/ngrok/

![wernight docker ngrok an ngrok v2 container based on wizardapps ngrok and fnichol ngrok](https://user-images.githubusercontent.com/412895/42862757-171f006a-8a8b-11e8-87c1-1fd601deae22.png)

**Comment by wernight** [comment]
Done
