### ISSUE TITLE
Receive ngrok url

### ISSUE THREAD

**Issue by jarkt** [wernight/docker-ngrok#54]
Is there a way to get the assigned ngrok url (foobar.ngrok.io)?
Maybe with an API call against the ngrok container?
I need the value as an envionment value in another container. Currently I have to configure it manually.

**Comment by jarkt** [comment]
Oh there it is, just slipped while reading. :-)
`curl $(docker port www_ngrok 4040)/api/tunnels`

**Comment by guicara** [comment]
And if you want to extract directly the URL from the JSON, you can use this script:

```
curl -s $(docker port www_ngrok 4040)/api/tunnels/command_line | grep -o '"public_url": *"[^"]*"' | grep -o '"[^"]*"$' | sed -e 's/^"//' -e 's/"$//'
```

**Comment by jarkt** [comment]
Parsing JSON with jq is much more readable.
I use it in a docker environment and need the url in the webserver container.
The webserver container has an entrypoint.sh, looking like this:
```
echo Get ngrok tunnel url...
export WEBHOOK_BASE_URL=$(bash /scripts/ngrok_url.sh)

echo Start webserver...
apache2-foreground
```

In ngrok_url.sh I have to wait that I can retrieve the url:
```
function echoUrl {
  ngrok_tunnels=$(curl -s http://ngrok:4040/api/tunnels)
  index=$(echo $ngrok_tunnels | jq '.tunnels | map(.proto == "https") | index(true)')
  echo $ngrok_tunnels | jq -r ".tunnels[$index].public_url"
}

n=0
until [ "$n" -ge 5 ]
do
  echoUrl && break
  n=$((n+1))
  sleep 5
done
```

**Comment by guicara** [comment]
I agree with you, `jq` is more readable.

However, `jq` is not always available by default on all distros. This is why I've used `grep` and `sed` instead. Telling my team to install an additional package was not an option for me.

**Comment by DinoChiesa** [comment]
FYI, when I use `$(curl -s http://ngrok:4040/api/tunnels)` , I get some HTML markup prepended to the JSON:

```
$ curl $(docker port ngrok 4040)/api/tunnels -H accept:application/json
<a href="/inspect/http">Found</a>.

{"tunnels":[{"name":"command_line","ID":"e58c669d2b47263baac050bab9ae3689","....
```

Which means the jq option doesn't work. This might be because ngrok is running in a container.... not sure.
