### ISSUE TITLE
transfer maintainership to ngrok?

### ISSUE THREAD

**Issue by zach-sherman** [wernight/docker-ngrok#63]
Hi @wernight you've built a great ngrok docker image here, and we'd love to use it for the official docker image ngrok releases and maintains. Would you be willing to transfer ownership of that repository to my github account so I can add it to the official @ngrok organization? If we do that, links across the internet will continue working, folks will be able to find the latest source, and we'll be better able to preserve your git history. Would you be amenable to this?

**Comment by zach-sherman** [comment]
bump ^

**Comment by TheSamDickey** [comment]
This would be incredible!  Ngrok is so underrated and this would make it even better :D

**Comment by zach-sherman** [comment]
It looks like we'll probably go with a much smaller entrypoint, so there's no real reason to transfer ownership. Sorry to bother!
