### ISSUE TITLE
How to always running this container...

### ISSUE THREAD

**Issue by dotMastaz** [wernight/docker-ngrok#8]
Hello,

First, thank you for this great job !!
I run your container, ngrok launch and website is available, ok...
But the process don't give me the hand and if i quit (CTRL+C), ngrok stop... How to launch your container and this don't stop...?

Thank you !

**Comment by wernight** [comment]
`docker -d ...` see docker CLI options.

**Comment by dotMastaz** [comment]
It's "--detach" option ?
Thank you !
