### ISSUE TITLE
NGROK_HOSTNAME or NGROK_DOMAIN?

### ISSUE THREAD

**Issue by IsaiahJTurner** [wernight/docker-ngrok#9]
Documentation says `NGROK_DOMAIN` but the code only allows for `NGROK_HOSTNAME`.

**Comment by wernight** [comment]
Where does it say `NGROK_HOSTNAME` on the documentation https://github.com/wernight/docker-ngrok ?

**Comment by IsaiahJTurner** [comment]
Nowhere, that's what the issue is.

**Comment by wernight** [comment]
Thanks
